typography_spectrum: 0.08002145
color:
  saturation: 0
  brandStrength: 1
  rhythmicContrast: 0
  brandColors:
    - '#010101'
    - '#ffffff'
    - '#cbcbcb'
    - '#6a6a6a'
    - '#444444'
  lightness: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.9500536
analytics:
  twitter: null
  google: null
  facebook: null
name: Crowded Elevator
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Crowded Elevator Pictures
description: 'Funny Business, Inc.'
purpose: []
