collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 1
  lightness: 0
  brandColors:
    - '#000001'
    - '#FFFFFF'
    - '#6C696F'
    - '#2F2E31'
    - '#C6C5C8'
  rhythmicContrast: 1
typography_spectrum: 0.3850698
layout_spectrum: 0.5322234
name: Crowded Elevator
