typography_spectrum: 0.07572501
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0
title: Crowded Elevator Pictures
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0
  brandStrength: 1
  rhythmicContrast: 0
  brandColors:
    - '#000001'
    - '#FFFFFF'
    - '#6B6B6D'
    - '#312F2F'
    - '#D0D0D0'
  lightness: 0.5
purpose: []
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Crowded Elevator
